-- CREATE TABLE ORDER_HISTORY(
--   ID NUMERIC(20,0) NOT NULL CONSTRAINT PK_ORDER_HISTORY PRIMARY KEY AS IDENTITY (START WITH 1000 INCREMENT BY 1),
--   ORDER_ID NUMERIC(20,0) NOT NULL,
--   DOCTOR_ID NUMERIC(6,0) NOT NULL,
--   CREATION_DATE DATE WITH DEFAULT CURRENT DATE
-- );
--
-- CREATE TABLE ANALYSES_HISTORY(
--   ID NUMERIC(20,0) NOT NULL CONSTRAINT PK_ANALYSIS_HISTORY PRIMARY KEY AS IDENTITY (START WITH 1000 INCREMENT BY 1) NOT NULL,
--   ORDER_HISTORY_ID NUMERIC(20,0) CONSTRAINT FK_ANALYSES_HISTORY_ORDER_HISTORY REFERENCES ORDER_HISTORY(ID) ON DELETE CASCADE,
--   ANALYSES_NUMBER NUMERIC(5,0) NOT NULL
-- );


-- Failed to load definition
-- [SQL0204] DB2LK_GENERATE_DDL in SYSPROC type *N not found.
-- auto-generated definition
CREATE TABLE ORDER_HISTORY
(
    ID BIGINT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1)  ,
    ORDER_ID BIGINT NOT NULL,
   CREATION_DATE DATE  DEFAULT   CURRENT_DATE  ,
    ORDER_HISTORY_KEY VARCHAR(255)
);
CREATE UNIQUE INDEX ORDER_HISTORY ON ORDER_HISTORY();


CREATE TABLE ORDER_ITEM_HISTORY
(
    ID BIGINT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1),
    ORDER_HISTORY_ID BIGINT,
    ORDER_ITEM_NUMBER VARCHAR(255),
    ORDER_ITEM_TYPE VARCHAR(255) DEFAULT 'ANALYSIS' NOT NULL,
    CONSTRAINT FK_ANALYSES_HISTORY_ORDER_HISTORY FOREIGN KEY (ORDER_HISTORY_ID) REFERENCES ORDER_HISTORY (ID) ON DELETE CASCADE
);
CREATE UNIQUE INDEX ORDER_ITEM_HISTORY ON ORDER_ITEM_HISTORY();