
-- CREATE TABLE SAMPLE_HISTORY(
--   ID NUMERIC(20,0) NOT NULL CONSTRAINT PK_MATERIAL_HISTORY PRIMARY KEY AS IDENTITY (START WITH 1000 INCREMENT BY 1) NOT NULL,
--   MATERIAL_ID NUMERIC(20,0) CONSTRAINT FK_SAMPLE_HISTORY_MATERIAL REFERENCES MATERIAL(ID) ON DELETE CASCADE,
--   COMBINATION_HASH VARCHAR(255) NOT NULL
-- );
--
-- CREATE TABLE ORDER_HISTORY_SAMPLE_HISTORY(
-- 	ORDER_HISTORY_ID NUMERIC(20,0) CONSTRAINT FK_ORDER_HISTORY REFERENCES ORDER_HISTORY(ID) ON DELETE CASCADE,
-- 	SAMPLE_HISTORY_ID NUMERIC(20,0) CONSTRAINT FK_SAMPLE_HISTORY REFERENCES SAMPLE_HISTORY(ID) ON DELETE CASCADE
-- );
--
-- CREATE TABLE MICROBIOLOGY_ANALYSIS_HISTORY(
--   ID NUMERIC(20,0) NOT NULL CONSTRAINT PK_MICROBIOLOGY_ANALYSIS_HISTORY PRIMARY KEY AS IDENTITY (START WITH 1000 INCREMENT BY 1) NOT NULL,
--   SAMPLE_HISTORY_ID NUMERIC(20,0) CONSTRAINT FK_MICROBIOLOGY_ANALYSIS_HISTORY_SAMPLE_HISTORY REFERENCES SAMPLE_HISTORY(ID) ON DELETE CASCADE,
--   ANALYSES_ID NUMERIC(5,0) NOT NULL,
--   ANALYSES_NUMBER NUMERIC(5,0) NOT NULL,
--   RECIPIENT VARCHAR(3) NOT NULL
-- );

CREATE TABLE SAMPLE_HISTORY
(
    ID BIGINT PRIMARY KEY   NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) ,
    MATERIAL_ID BIGINT,
    COMBINATION_HASH VARCHAR(255) NOT NULL,
    HASH_MIGRATED CHAR(1) DEFAULT 'N'
   -- , CONSTRAINT FK_SAMPLE_HISTORY_MATERIAL FOREIGN KEY (MATERIAL_ID) REFERENCES MB_MATERIAL (ID) ON DELETE CASCADE
);
-- CREATE UNIQUE INDEX SAMPLE_HISTORY ON SAMPLE_HISTORY();

CREATE TABLE MICROBIOLOGY_ANALYSIS_HISTORY
(
    ID BIGINT PRIMARY KEY   NOT NULL  GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) ,
    ANALYSES_ID BIGINT NOT NULL,
    ANALYSES_NUMBER BIGINT NOT NULL,
    RECIPIENT VARCHAR(3) NOT NULL
);
-- CREATE UNIQUE INDEX MICROBIOLOGY_ANALYSIS_HISTORY ON MICROBIOLOGY_ANALYSIS_HISTORY();

CREATE TABLE SAMPLE_HISTORY_MICROBIOLOGY_ANALYSIS_HISTORY
(
    SAMPLE_HISTORY_ID BIGINT,
    MICROBIOLOGY_ANALYSIS_HISTORY_ID BIGINT,
    CONSTRAINT FK_SAMPLE_HISTORY_MICROBIOLOGY_KEY1 FOREIGN KEY (MICROBIOLOGY_ANALYSIS_HISTORY_ID) REFERENCES MICROBIOLOGY_ANALYSIS_HISTORY (ID) ON DELETE CASCADE,
    CONSTRAINT FK_SAMPLE_HISTORY_MICROBIOLOGY_KEY2 FOREIGN KEY (SAMPLE_HISTORY_ID) REFERENCES SAMPLE_HISTORY (ID) ON DELETE CASCADE
);

