
-- CREATE TABLE PATHOLOGY_SAMPLE_HISTORY (
--   ID                       NUMERIC(20, 0) NOT NULL CONSTRAINT PK_PATHOLOGY_SAMPLE_HISTORY PRIMARY KEY AS IDENTITY (START WITH 1000 INCREMENT BY 1),
--   PATHOLOGY_MATERIAL_ID    NUMERIC(20, 0) NOT NULL CONSTRAINT FK_PATHOLOGY_SAMPLE_HISTORY_TO_MATERIAL REFERENCES PATHOLOGY_MATERIAL (ID) ON DELETE CASCADE,
--   LOCATION                 VARCHAR(100) NOT NULL,
--   COMBINATION_HASH         VARCHAR(32) NOT NULL UNIQUE
-- );
--
-- CREATE TABLE ORDER_HISTORY_PATHOLOGY_SAMPLE_HISTORY (
--   ORDER_HISTORY_ID         NUMERIC(20, 0) NOT NULL CONSTRAINT FK_ORDER_HISTORY_PATHLOGY_SAMPLE REFERENCES ORDER_HISTORY (ID),
--   PATHOLOGY_SAMPLE_HISTORY_ID      NUMERIC(20, 0) NOT NULL CONSTRAINT FK_PATHOLOGY_SAMPLE_ORDER_HISTORY REFERENCES PATHOLOGY_SAMPLE_HISTORY (ID) ON DELETE CASCADE
-- );


CREATE TABLE PATHOLOGY_IMAGE_HISTORY
(
    ID BIGINT PRIMARY KEY   NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1),
    ORDER_HISTORY_ID BIGINT,
    IMAGE VARCHAR(256) NOT NULL,
    CONSTRAINT FK_PATHOLOGY_IMAGE_HISTORY_ORDER_HISTORY FOREIGN KEY (ORDER_HISTORY_ID) REFERENCES ORDER_HISTORY (ID) ON DELETE CASCADE
);
-- CREATE UNIQUE INDEX PATHOLOGY_IMAGE_HISTORY ON PATHOLOGY_IMAGE_HISTORY();

CREATE TABLE PATHOLOGY_MATERIAL_HISTORY
(
    ID BIGINT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1),
    ORDER_HISTORY_ID BIGINT,
    PATHOLOGY_MATERIAL_ID BIGINT,
    CONSTRAINT FK_PATHOLOGY_MATERIAL_HISTORY_ORDER_HISTORY FOREIGN KEY (ORDER_HISTORY_ID) REFERENCES ORDER_HISTORY (ID) ON DELETE CASCADE
--   ,  CONSTRAINT FK_PATHOLOGY_MATERIAL_HISTORY_PATHOLOGY_MATERIAL FOREIGN KEY (PATHOLOGY_MATERIAL_ID) REFERENCES PATHOLOGY_MATERIAL (ID) ON DELETE CASCADE
);
-- CREATE UNIQUE INDEX PATHOLOGY_MATERIAL_HISTORY ON PATHOLOGY_MATERIAL_HISTORY();