WITH DECLARATION (PROCEDURE_NAME, PARAM_LIST, RECURSION_DEPTH, PARAM_COUNT) AS
( SELECT
    PROCEDURE_NAME,
    '',
    0,
    PROC.NUM_INPUT_PARAMS
  FROM SYSIBM.SQLPROCEDURES PROC
  WHERE PROC.PROCEDURE_SCHEM = ?

  UNION ALL

  SELECT
    DECLARATION.PROCEDURE_NAME,
    CASE
--     WHEN DECLARATION.RECURSION_DEPTH = 0 AND DECLARATION.PARAM_COUNT = 1
--       THEN
--         '(' || PROCPARAM.TYPE_NAME || ')'
    WHEN DECLARATION.RECURSION_DEPTH = 0
      THEN
         CASE WHEN TYPE_NAME = 'NUMERIC' THEN TYPE_NAME || '(' || COLUMN_SIZE ||',' || DECIMAL_DIGITS || ')' WHEN TYPE_NAME = 'VARCHAR' THEN TYPE_NAME || '(' || COLUMN_SIZE ||')' ELSE TYPE_NAME END
--     WHEN DECLARATION.RECURSION_DEPTH + 1 = DECLARATION.PARAM_COUNT
--       THEN
--         DECLARATION.PARAM_LIST || ',' || PROCPARAM.TYPE_NAME || ')'
    ELSE
      DECLARATION.PARAM_LIST || ',' || CASE WHEN TYPE_NAME = 'NUMERIC' THEN TYPE_NAME || '(' || COLUMN_SIZE ||',' || DECIMAL_DIGITS || ')' WHEN TYPE_NAME = 'VARCHAR' THEN TYPE_NAME || '(' || COLUMN_SIZE ||')' ELSE TYPE_NAME END
    END PARAMS,
    DECLARATION.RECURSION_DEPTH + 1,
    DECLARATION.PARAM_COUNT

  FROM DECLARATION, SYSIBM.SQLPROCEDURECOLS PROCPARAM
  WHERE PROCPARAM.PROCEDURE_SCHEM = ?
        AND PROCPARAM.PROCEDURE_NAME = DECLARATION.PROCEDURE_NAME
        AND DECLARATION.RECURSION_DEPTH < DECLARATION.PARAM_COUNT
        AND PROCPARAM.ORDINAL_POSITION = DECLARATION.RECURSION_DEPTH + 1
)
SELECT DISTINCT
  PROCEDURE_NAME,
  PARAM_LIST
FROM DECLARATION
WHERE RECURSION_DEPTH = PARAM_COUNT